export const INIT_STATELIST="STATE.INIT_STATELIST";
export const INIT_STATEVIEW="STATE.INIT_STATEVIEW";
export const INIT_STATEEDIT="STATE.INIT_STATEEDIT";
export const INIT_STATEUPDATE="STATE.INIT_STATEUPDATE";
export const LOADING="STATE.LOADING";
export const ERROR="STATE.ERROR";